// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IGb_Rqi824YiRevkxxHiCwi0TTgUlKQ',
    appId: '1:1066961223051:web:7e91b35f9f72506b0b838e',
    messagingSenderId: '1066961223051',
    projectId: 'chatapp-59934',
    authDomain: 'chatapp-59934.firebaseapp.com',
    storageBucket: 'chatapp-59934.appspot.com',
    measurementId: 'G-KLK5DFY88J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVYBTcMFusH6AGmahf-y8hcJ2aPcMEsY',
    appId: '1:1066961223051:android:0eeb18ccd1c1ed9e0b838e',
    messagingSenderId: '1066961223051',
    projectId: 'chatapp-59934',
    storageBucket: 'chatapp-59934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGsd1hvLxWrZfc5Zn_rWdtSJ0dVNI2iY',
    appId: '1:1066961223051:ios:ab5db7595d08d5e00b838e',
    messagingSenderId: '1066961223051',
    projectId: 'chatapp-59934',
    storageBucket: 'chatapp-59934.appspot.com',
    iosClientId: '1066961223051-f3qiphuvdnbp82anh0lcbulharbr1cnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
